name: Build and Push Docker image

on:
  push:
    branches: [ main ]  # or your preferred branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: debian
          file: debian/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/bedrock-debian:latest

  build-and-push-satisfactory:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Satisfactory Docker image
        uses: docker/build-push-action@v5
        with:
          context: steamcmd/debian-satisfactory
          file: steamcmd/debian-satisfactory/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/satisfactory-debian:latest